# Generated by Django 2.0.6 on 2018-10-20 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundBaseCollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('song_title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('comment_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('release_date', models.DateTimeField(default=datetime.datetime.now)),
                ('download_count', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('full_duration', models.IntegerField(default=0)),
                ('playback_count', models.IntegerField(default=0)),
                ('reposts_count', models.IntegerField(default=0)),
                ('tag_list', models.CharField(default='Electronic, Deep House', max_length=3000)),
                ('uri', models.CharField(default='Not included', max_length=200)),
                ('used', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='full_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='playback_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='reposts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='tag_list',
            field=models.CharField(default='Electronic, Deep House', max_length=3000),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='uri',
            field=models.CharField(default='Not included', max_length=200),
        ),
        migrations.AddField(
            model_name='electronicdata',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
