# Generated by Django 2.0.6 on 2018-10-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundBaseCollection', '0002_auto_20181020_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicbase',
            name='Artist',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='electronicdata',
            name='Artist',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
