# Generated by Django 2.0.6 on 2018-10-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundBaseCollection', '0003_auto_20181020_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicbase',
            name='song_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electronicbase',
            name='uri',
            field=models.CharField(default='Not included', max_length=400),
        ),
        migrations.AlterField(
            model_name='electronicdata',
            name='song_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electronicdata',
            name='uri',
            field=models.CharField(default='Not included', max_length=400),
        ),
    ]
